
import React from 'react';

interface ImageDisplayProps {
  imageUrl: string | null;
}

const PlaceholderIcon: React.FC = () => (
    <svg xmlns="http://www.w3.org/2000/svg" className="h-24 w-24 text-slate-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
    </svg>
);


export const ImageDisplay: React.FC<ImageDisplayProps> = ({ imageUrl }) => {
  return (
    <div className="aspect-square w-full bg-slate-900/50 rounded-lg flex items-center justify-center overflow-hidden border border-slate-700 transition-all duration-300">
      {imageUrl ? (
        <img
          src={imageUrl}
          alt="Generated by AI"
          className="w-full h-full object-contain"
        />
      ) : (
        <div className="text-center text-slate-500">
          <PlaceholderIcon />
          <p className="mt-2">Your generated image will appear here</p>
        </div>
      )}
    </div>
  );
};
